[pytest]
testpaths = fact_check_agent/tests
pythonpath = memory_agent fact_check_agent
addopts = -p no:launch_testing -p no:launch_testing_ros -p no:launch_testing_ros_pytest_entrypoint -p no:ament_pep257 -p no:ament_copyright -p no:ament_xmllint -p no:ament_lint -p no:ament_flake8 -p no:colcon_core
